const initialState = {
    csvFiles: [],
    path: [],
    columnData: [],
    dataAttributes: [],
    attributeMappingData: [],
    isFriendlyName: false,
    ftpConnectionStatus: false,
    bgQueryConnectData: [],
    bqConnected: [],
    showBQTable: [],
    headerColumns: '',
    audienceCount: 0,
    attributeMapping: '',
    categoryTypeText: '',
    controlConnection: false,
    responseHeaders: '',
    fileWiseListAnalysisData: {},
    mappingDataLoading: false,
    excelFilesData: [],
    insightData: {},
    childCategoryList: [],
};

export default initialState;
