const initialState = {
    activeTab: 0,
    clientType:'B2C',
    purchasePattern: {
        defaultValues: {
            frequency: [{ less: '2', more: '5', score: '11' }],
            purchaseWorth: [{ less: '1000', more: '5000', score: '20' }],
            grading: [{ belove: '', above: '', score: '' }],
            recency: {
                recency_1_to_3_days: '',
                week: '20',
                month: '20',
                quarter: '20',
                more_6_months: '20',
            },
            aaaaa: 'ewefew',

            frequencyLessThanScore: '5',
            frequencyMoreThanScore: '20',
            purchasePriseBelow: '1000',
            purchasePriseAbove: '5000',
            purchasePriseBelowScore: '10',
            purchasePriseAboveScore: '30',
            gradingAboveScore: 'B',
            gradingBelowScore: 'C',
            gradingAbove: '50',
            gradingBelow: '10',
            gradingFromOne: '40',
            gradingToOne: '30',
            gradingFromTwo: '40',
            gradingToTwo: '20',
            gradingScoreOne: 'D',
            gradingScoreTwo: 'C',
            recencyTotal: '80',
            recencyCollapse: false,
            frequencyTotal: '10',
            purchaseWorthTotal: '100',
            frequencybetweenData: {
                lessValue: '2',
                moreValue: '5',
                lessScore: '10',
                moreScore: '20',
            },
            purchaseWorthbetweenData: {
                lessValue: '1000',
                moreValue: '5000',
                lessScore: '15',
                moreScore: '30',
            },
        },
        values: {
            recency: {
                recency_1_to_3_days: '12',
                week: '20',
                month: '20',
                quarter: '20',
                more_6_months: '20',
            },
        },
        mode: 'onTouched',
    },
    profileData: {
        defaultValues: {
            dataArguments: {
                ageGroup: '20',
                gender: '20',
                income: '20',
                location: '20',
                education: '20',
            },
            omnichannel: {
                email: '20',
                sms: '20',
                whatsApp: '20',
                facebook: '20',
                twitter: '20',
            },
            referal: {
                email: '20',
                sms: '20',
                whatsApp: '20',
                facebook: '20',
                twitter: '20',
            },
            networkWorth: {
                linkedin: '10',
                facebook: '10',
                twitter: '20',
                instagram: '20',
                youtube: '30',
            },
            networkWorthAbove: {
                linkedin: '10',
                facebook: '10',
                twitter: '20',
                instagram: '20',
                youtube: '30',
            },
            gradingAboveScore: 'B',
            gradingBelowScore: 'C',
            gradingAbove: '50',
            gradingBelow: '10',
            gradingFromOne: '40',
            gradingToOne: '30',
            gradingFromTwo: '40',
            gradingToTwo: '20',
            gradingScoreOne: 'D',
            gradingScoreTwo: 'C',
            dataArgumentsTotal: '100',
            omnichannelTotal: '100',
            referalTotal: '100',
            networkWorthTotal: '100',
        },
    },
    communicationResponse: {
        defaultValues: {
            reach: [
                { reachData: 'A', reachValue: '10' },
                { reachData: 'B', reachValue: '15' },
                { reachData: 'C', reachValue: '20' },
            ],
            engagement: [
                { engagementData: 'A', engagementValue: '10' },
                { engagementData: 'B', engagementValue: '15' },
                { engagementData: 'C', engagementValue: '20' },
            ],
            conversion: [
                { conversionData: 'A', conversionValue: '10' },
                { conversionData: 'B', conversionValue: '15' },
                { conversionData: 'C', conversionValue: '20' },
            ],
            campaignDetails: [
                { campaignDetailsData: 'A', campaignDetailsValue: '10' },
                { campaignDetailsData: 'B', campaignDetailsValue: '15' },
                { campaignDetailsData: 'C', campaignDetailsValue: '20' },
            ],
            goal: [{ less: '10', more: '15', score: '20' }],
            goalMoreThan: '30',
            goalOnce: '10',
            brandSentiment: {
                positive: '20',
                neutral: '25',
                negative: '-24',
            },
            goalbetweenData: {
                lessScore: '10',
                moreScore: '20',
            },
        },
    },
    audienceLaddering: {
        defaultValues: {
            advocates: {
                communicationsSent: '10',
                communicationsEngaged: '20',
                participation: '20',
                campaGoalsAchieved: '20',
                profileCompleteness: '10',
                networkWorth: '30',
                referralScore: '20',
                brandSentiment: '10',
                fanofBrand: '20',
            },
            influencers: {
                communicationsSent: '10',
                communicationsEngaged: '20',
                participation: '20',
                campaGoalsAchieved: '20',
                profileCompleteness: '10',
                networkWorth: '30',
                referralScore: '20',
                brandSentiment: '10',
                fanofBrand: '20',
            },
            critics: {
                communicationsSent: '10',
                communicationsEngaged: '20',
                participation: '20',
                campaGoalsAchieved: '20',
                profileCompleteness: '10',
                networkWorth: '30',
                referralScore: '20',
                brandSentiment: '10',
                fanofBrand: '20',
            },
            spectators: {
                communicationsSent: '10',
                communicationsEngaged: '20',
                participation: '20',
                campaGoalsAchieved: '20',
                profileCompleteness: '10',
                networkWorth: '30',
                referralScore: '20',
                brandSentiment: '10',
                fanofBrand: '20',
            },
        },
    },
    audienceCardCollapse: {},
};

export default initialState;
