const initialState = {
    smsData: [],
    settingsProviders: [],
    whatsAppGrid: [],
    rcsGrid: [],
    subscribeData: [],
    unSubscribeData: [],
    isCreated : false,
    subscribeUpdateData: {},
    vmsData: [],
    lineData: [],
    segmentList: [],
    communicationTypes: [],
    personaList: [],
    getWebPushAnalyticsListData: [],
    isBUEnableSub:0,
    isBUEnablePush:0,
    isBUEnableAds:0,
    appDeviceList: [],
    appLanguageList: [],
    analyticsListMobile: [],
    audienceGroupList: [],
    selectAudienceGroup: [],
    ruleTypeList: [],
    disableBU: false,
    RCSsettingsProviders: [],
    optInOutList: [],
    optInOutSenderList: [],
    complianceKeywordsList: [],
    fallbackMessageData: [],
    customKeywordsList: [],
    inboundActionTypes: [],
    optInOutCountryId: null,
    keywordManagementLoading: false,
    complianceKeywordsLoading: false,
    fallbackMessageLoading: false,
    customKeywordsLoading: false,
    inboundListLoading: false,
};

export default initialState;
