const REGION = [
    { id: 1, name: 'New york' },
    { id: 2, name: 'Loss angel' },
    { id: 3, name: 'Chicago' },
    { id: 4, name: 'Sydney' },
    { id: 5, name: 'Nagpur' },
];

const GOAL = [
    { id: 1, name: 'Reach' },
    { id: 2, name: 'Engagement' },
    { id: 3, name: 'Conversion' },
];

const CHANNEL = [
    { id: 1, name: 'E-mai' },
    { id: 2, name: 'Facebook' },
    { id: 3, name: 'SMS' },
    { id: 4, name: 'Twitter' },
];

const INDUSTRY = [
    { id: 1, name: 'Advertising' },
    { id: 2, name: 'Apparels' },
    { id: 3, name: 'Automotive' },
];

const MERCHANT = [
    { id: 1, name: 'Amazon' },
    { id: 2, name: 'Flipkart' },
    { id: 3, name: 'Reliance Digital' },
];

const CREDIT_CARD_ACQUISION = [
    { id: 1, name: 'Region', value: REGION },
    { id: 2, name: 'Goal', value: GOAL },
    { id: 3, name: 'Channel', value: CHANNEL },
    { id: 4, name: 'Industry', value: INDUSTRY },
    { id: 5, name: 'Merchant', value: MERCHANT },
];

export const INITIAL_STATE = {
    defaultValues: {
        acquisition: [{ acquisition: '', acquisitionOne: '', acquisitionTwo: '', acquisitionThree: '' }],
    },
};

const CHOOSE_CAMPAIGN = [
    {
        id: 1,
        name: 'Same Communication',
        timeInPosition: 0,
        position: 'Same Communication',
    },
    {
        id: 2,
        name: 'Credit card acquisition',
        timeInPosition: 0,
        position: 'Golden Communication',
    },
    {
        id: 3,
        name: 'Grow your wealth',
        timeInPosition: 1,
        position: 'Golden Communication',
    },
    {
        id: 4,
        name: 'Reliance Big Bonanza Sale',
        timeInPosition: 0,
        position: 'Other Communications',
    },
    {
        id: 5,
        name: 'Gold bonds',
        timeInPosition: 1,
        position: 'Other Communications',
    },
];

const PERIOD = ['1', '2', '3', '4', '5'];

const NOTESDATA = [
    {
        recipientAquisitionID: 28,
        eventChannelName: 'Email',
        eventDate: '5/6/2022',
        eventChannelDescription: 'Updated Email May 5/06/2022 Note',
        departmentID: 1,
        createdDate: '2022-10-05T08:28:30',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 29,
        eventChannelName: 'Mobile',
        eventDate: '5/6/2022',
        eventChannelDescription: 'Mobile Sample Acquisition Notes',
        departmentID: 1,
        createdDate: '2022-10-05T08:29:44',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 30,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note',
        departmentID: 1,
        createdDate: '2022-10-06T06:02:49',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 31,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note TEST',
        departmentID: 1,
        createdDate: '2022-10-06T06:05:56',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 32,
        eventChannelName: 'Emai2l',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note TEST2',
        departmentID: 1,
        createdDate: '2022-10-06T06:08:39',
        createdBy: 434,
        recipientAcquisitionDetails: '22',
    },
    {
        recipientAquisitionID: 33,
        eventChannelName: 'Email',
        eventDate: '5/23/2022',
        eventChannelDescription: 'Updated MAY 24th Note',
        departmentID: 1,
        createdDate: '2022-10-06T07:08:06',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 34,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note',
        departmentID: 1,
        createdDate: '2022-10-06T10:54:33',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 35,
        eventChannelName: 'Email',
        eventDate: '29-09-2022',
        eventChannelDescription: 'Email note',
        departmentID: 1,
        createdDate: '2022-10-06T11:05:48',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 36,
        eventChannelName: 'Mobile',
        eventDate: '05-10-2022',
        eventChannelDescription: 'Mobile note',
        departmentID: 1,
        createdDate: '2022-10-06T11:07:10',
        createdBy: 434,
        recipientAcquisitionDetails: '22',
    },
    {
        recipientAquisitionID: 37,
        eventChannelName: 'Email',
        eventDate: '4/29/2022',
        eventChannelDescription: 'Updated the Email Notes for April',
        departmentID: 1,
        createdDate: '2022-10-07T06:54:15',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 38,
        eventChannelName: 'Email',
        eventDate: '5/6/2022',
        eventChannelDescription: 'Updated the Sample Acqusition Notes\n',
        departmentID: 1,
        createdDate: '2022-10-07T07:27:56',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 39,
        eventChannelName: 'Email',
        eventDate: '5/23/2022',
        eventChannelDescription: 'Updated the notes for E-mail',
        departmentID: 1,
        createdDate: '2022-10-07T08:52:38',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 40,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'This is my Email Test Note',
        departmentID: 1,
        createdDate: '2022-10-07T09:09:32',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 41,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'This is my email Test Note',
        departmentID: 1,
        createdDate: '2022-10-07T09:35:10',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 42,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'This is hariram Test Note',
        departmentID: 1,
        createdDate: '2022-10-07T09:37:23',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 43,
        eventChannelName: 'Mobile',
        eventDate: '4/17/2022',
        eventChannelDescription: 'Created a new note for 4/17/2022',
        departmentID: 1,
        createdDate: '2022-10-07T11:58:59',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 44,
        eventChannelName: 'Email',
        eventDate: '10/12/2022',
        eventChannelDescription: 'This is a Sample Acqusition Notes',
        departmentID: 1,
        createdDate: '2022-10-17T12:28:33',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 45,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note',
        departmentID: 1,
        createdDate: '2022-10-18T10:41:56',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 46,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note',
        departmentID: 1,
        createdDate: '2022-10-18T10:50:26',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 47,
        eventChannelName: 'Email',
        eventDate: '23-09-2022',
        eventChannelDescription: 'Email note',
        departmentID: 1,
        createdDate: '2022-10-19T05:26:30',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
    {
        recipientAquisitionID: 48,
        eventChannelName: 'Email',
        eventDate: '10/19/2022',
        eventChannelDescription: 'This is a new Acqistion notes',
        departmentID: 1,
        createdDate: '2022-11-07T06:08:37',
        createdBy: 434,
        recipientAcquisitionDetails: '21',
    },
];

export { CHOOSE_CAMPAIGN, CREDIT_CARD_ACQUISION, REGION, GOAL, CHANNEL, INDUSTRY, MERCHANT, PERIOD, NOTESDATA };
