import { alexa_large, builder_attachment_large, builder_button_large, builder_checkbox_large, builder_date_time_large, builder_divider_large, builder_image_large, builder_text_large, builder_video_large, user_arrow_down_large, user_call_center_large } from 'Constants/GlobalConstant/Glyphicons';
export const LANDING_PAGE_ELEMENTS = [
    {
        id: 1,
        icon: user_arrow_down_large,
        label: 'Blocks',
        clicked: false,
        component: (index) => <Blocks index={index} />,
    },
    {
        id: 2,
        icon: user_call_center_large,
        label: 'Section',
        clicked: false,
        component: (index) => <SectionElement index={index} />,
    },
    {
        id: 3,
        icon: alexa_large,
        label: 'Heading',
        clicked: false,
        component: (index) => <Heading index={index} />,
    },
    {
        id: 4,
        icon: builder_text_large,
        label: 'Text',
        clicked: false,
        component: (index) => <TextElement index={index} />,
    },
    {
        id: 5,
        icon: builder_image_large,
        label: 'Image',
        clicked: false,
        component: (index) => <ImageElement index={index} />,
    },
    {
        id: 6,
        icon: builder_video_large,
        label: 'Video',
        clicked: false,
        component: (index) => <VideoElement index={index} />,
    },
    {
        id: 7,
        icon: builder_button_large,
        label: 'Button',
        clicked: false,
        component: (index) => <Buttons index={index} />,
    },
    {
        id: 8,
        icon: builder_attachment_large,
        label: 'Link Block',
        clicked: false,
        component: (index) => <LinkBlock index={index} />,
    },
    {
        id: 9,
        icon: builder_divider_large,
        label: 'Divider',
        clicked: false,
        component: (index) => <Divider index={index} />,
    },
    {
        id: 10,
        icon: builder_checkbox_large,
        label: 'Icon',
        clicked: false,
        component: (index) => <Icons index={index} />,
    },
    {
        id: 11,
        icon: builder_date_time_large,
        label: 'Timer',
        clicked: false,
        component: (index) => <TimerElement index={index} />,
    },
];
