import { HorizontalSkeleton, PieChartSkeleton } from 'Components/Skeleton/Skeleton';
import { CTR, PROJECTED_CTR, SUBJECT_LINE_ANALYSIS, SUBJECT_LINE_LENGTH, TOP3_SUBJECT_LINES } from 'Constants/GlobalConstant/Placeholders';
import { useEffect } from 'react';
import { Container } from 'react-bootstrap';
import _get from 'lodash/get';
import { useDispatch, useSelector } from 'react-redux';
import RSHighchartsContainer from 'Components/Highcharts';
import RSModal from 'Components/RSModal';
import { ctrColor, percentageChartOptions, subjectColor } from './constant';
import useQueryParams from 'Hooks/useQueryParams';
import { getSubjectLineAnalysis } from 'Reducers/communication/createCommunication/Create/request';
import { getSessionId } from 'Reducers/globalState/selector';
const SubjectLineAnalysisModal = ({ show, handleClose, subjectLineText }) => {
    const dispatch = useDispatch();
    const location = useQueryParams('/communication');
    const { clientId, userId, departmentId } = useSelector((state) => getSessionId(state));
    let { emailList } = useSelector(({ createCommunicationReducer }) => createCommunicationReducer);

    const campaign = {
        campaignId: _get(location, 'campaignId', 0),
        campaignProductType: _get(location, 'productType', ''),
        campaignCommunicationType: _get(location, 'communicationType', ''),
    };

    useEffect(() => {
        //  setShow(show);
        if (show) {
            dispatch(
                getSubjectLineAnalysis({
                    loading: false,
                    payload: {
                        userId,
                        clientId,
                        departmentId,
                        campaignType: campaign?.campaignCommunicationType,
                        productType: campaign?.campaignProductType,
                        subjectLine: subjectLineText,
                    },
                }),
            );
        }
    }, [show]);
    let temptopLines =
        "Congratulations Customer! You've won IND vs NZ Match tickets! ?&&Congratulations! You've won IND vs AUS Chennai ODI Match tickets! ?&&Congratulations! You've won IND vs AUS Vizag ODI Match tickets! ?".split(
            '&&',
        );
let cons = {
        "status": "success",
        "originalAnalysis": {
            "subjectLine": "dp email adhoc blast jun 03",
            "unifiedPerformanceScore": 0.61,
'subject_line_length':0
        },
        "generatedVariants": [
            {
                "rank": 1,
                "subjectLine": "Fresh June Offers Await 🎁",
                "score": 0.62,
                "projectedCtr": 0,
                "strategy": "Generative AI (External Server)",
                "improvement": "+0.01",
                "keyChanges": [
                    "Generated by External Server"
                ],
                "beatsOriginal": true
            },
            {
                "rank": 2,
                "subjectLine": "New for June 3rd: You In? 🌟",
                "score": 0.62,
                "projectedCtr": 0,
                "strategy": "Generative AI (External Server)",
                "improvement": "+0.01",
                "keyChanges": [
                    "Generated by External Server"
                ],
                "beatsOriginal": true
            },
            {
                "rank": 3,
                "subjectLine": "DP Update: June 3rd Alerts 📅",
                "score": 0.61,
                "projectedCtr": 0,
                "strategy": "Generative AI (External Server)",
                "improvement": "0.0",
                "keyChanges": [
                    "Generated by External Server"
                ],
                "beatsOriginal": false
            }
        ]
    }

    let maxOpenRates = emailList?.subjectLine_Analysis[0]?.maxOpenRates ? emailList?.subjectLine_Analysis[0]?.maxOpenRates?.split('&&') || [] : []
    const newObj = [],
        newobj1 = [];

    maxOpenRates?.forEach((eachArrayElement, index) => {
        const x = {
            percent: eachArrayElement,
            id: index,
        };
        newObj.push(x);
    });
    // emailList?.subjectLine_Analysis[0]?.topLines
    const topLines =emailList?.subjectLine_Analysis[0]?.generatedVariants// emailList?.subjectLine_Analysis[0]?.topLines ? emailList?.subjectLine_Analysis[0]?.topLines.split('&&') || [] : [];
    topLines?.forEach((eachArrayElement, index) => {
        const x = {
            id: index,
            text: eachArrayElement?.subjectLine,
            percent: eachArrayElement?.score,
        };
        newobj1.push(x);
    });

    const resultTop3lines = newobj1?.map((v) => ({ ...v, ...newObj.find((sp) => sp.id === v.id) }));

    const wordRecommendation = '';

    return (
        <RSModal
            show={show}
            handleClose={handleClose}
            size="lg"
            header={SUBJECT_LINE_ANALYSIS}
            body={
                <Container className="emojifont">
                    <p className="fs19">{subjectLineText}</p>
                    <>
                        <div
                            className={`sla-modal-content mt32 ${
                                emailList?.subjectLine_Analysis[0]?.openRate || emailList?.subjectLine_Analysis?.unifiedPerformanceScore? '' : 'mb32 align-items-baseline'
                            } `}
                        >
                            <div className="slamc-block slamcb-left">
                                <span className="slamcb-heading">{PROJECTED_CTR}</span>
                                <div
                                    className={`profileCompleteChart ${
                                        emailList?.subjectLine_Analysis[0]?.openRate|| emailList?.subjectLine_Analysis?.unifiedPerformanceScore ? '' : 'mt20'
                                    }`}
                                >
                                    {emailList?.subjectLine_Analysis[0]?.openRate|| emailList?.subjectLine_Analysis?.originalAnalysis?.unifiedPerformanceScore ? (
                                        <RSHighchartsContainer
                                            options={percentageChartOptions(
                                               // Math.round(emailList?.subjectLine_Analysis[0]?.openRate) || 0,
                                                Math.round(emailList?.subjectLine_Analysis?.originalAnalysis?.unifiedPerformanceScore)||0,
                                                ctrColor,
                                            )}
                                            // className="sla-chart"
                                        />
                                    ) : (
                                        <PieChartSkeleton isError={true} noLegend customTop/>
                                    )}
                                </div>
                            </div>
                            <div className="slamc-block slamcb-right">
                                <span className="slamcb-heading">{SUBJECT_LINE_LENGTH}</span>
                                <div className="profileCompleteChart">
                                    {emailList?.subjectLine_Analysis[0]?.lengthPercentile|| emailList?.subjectLine_Analysis?.originalAnalysis?.subject_line_length ? (
                                        <RSHighchartsContainer
                                            options={percentageChartOptions(
                                               // Math.round(emailList?.subjectLine_Analysis[0]?.lengthPercentile) || 0,
                                                 Math.round(emailList?.subjectLine_Analysis?.originalAnalysis?.subject_line_length)||0,
                                                subjectColor,
                                            )}
                                            // className="sla-chart"
                                        />
                                    ) : (
                                        <PieChartSkeleton isError={true} noLegend className="mt20" customTop />
                                    )}
                                </div>
                            </div>
                        </div>
                        <div className="sla-modal-content-items position-relative">
                            <div className="slamci-wrapper mb10">
                                <div className="slamciw-block slamciw-left">
                                    <h3 className="slamci-heading">{TOP3_SUBJECT_LINES}</h3>
                                </div>
                                {resultTop3lines?.length > 0 && (
                                    <div className="slamciw-block slamciw-right">
                                        <h3 className="slamci-heading text-center">
                                            {CTR}
                                            {/* <span className="font-xsm">%</span> */}
                                        </h3>
                                    </div>
                                )}
                            </div>
                            {resultTop3lines?.length ? (
                                <>
                                    {resultTop3lines.map((subject) => (
                                        <div className="slamci-wrapper" key={subject.id}>
                                            <div className="slamciw-block slamciw-left">{subject.text}</div>
                                            <div className="slamciw-block slamciw-right divider">
                                                {subject.percent || 0}
                                                <span className="percentage">%</span>
                                            </div>
                                        </div>
                                    ))}
                                </>
                            ) : (
                                <>
                                    <HorizontalSkeleton count={3} isError={true} />
                                </>
                            )}
                        </div>
                    </>
                </Container>
            }
            footer={false}
        />
    );
};

export default SubjectLineAnalysisModal;
