export const MDC_CHANNEL_AND_ACTION_TEMPLATE = {
    MDCChannel: [
        { email: 1, htmlId: 'ch001', value: 1 },
        { sms: 2, htmlId: 'ch002', value: 2 },
        { whatsApp: 2, htmlId: 'ch0021', value: 21 },
        { rcs: 2, htmlId: 'ch0041', value: 41 },
        { qrCode: 3, htmlId: 'ch003', value: 3 },
        { webNotification: 8, htmlId: 'ch008', value: 8 },
        { mobPushNotification: 14, htmlId: 'ch0014', value: 14 },
        { vms: 25, htmlId: 'ch0025', value: 25 },
        { voice: 26, htmlId: 'ch0026', value: 26 },
        { webhook: 34, htmlId: 'ch0034', value: 34 },
        { LandingPage: 'goal001', htmlId: 'goal001', value: 'goal001' },
        { LandingPage: 'goal002', htmlId: 'goal002', value: 'goal002' },
    ],
    MDCAction: {
        Unknown: 0,
        Open: 1,
        NotOpen: 2,
        Click: 3,
        NotClick: 4,
        Delivered: 5,
        UnDelivered: 6,
        Clicked: 7,
        Like: 8,
        Share: 9,
        View: 10,
        Favorite: 11,
        Retweet: 12,
        Follow: 13,
        Purchase: 14,
        NotPurchase: 15,
        ShoppingCartAbandon: 16,
        AddToWishList: 17,
        NewCustomer: 18,
        NewContact: 19,
        ContactUpdate: 20,
        Registered: 21,
        Notregistered: 22,
        NewRegister: 23,
        Attended: 24,
        NotAttended: 25,
        NotClickedOrNotVisit: 26,
        Visited: 30,
        Sent: 99,
        Success: 37,
        Userbusy: 38,
        Disconnected: 39,
        Ringtimeout: 40,
        Notreachable: 41,
        Expired: 42,
        Dismissed: 43,
        Maybelater: 44,
        Received: 45,
        NotReceived: 47,
        Scanned: 48,
        Read: 49,
        Responded: 50,
        Blocked: 51,
        Reported: 52,
        NotRead: 53,
    },
};
