const gridColumnData = [
    {
        field: 'userId',
        filtervalue: 'string',
        title: 'S.No',
        filter:'text',
    },
    {
        field: 'membership',
        filtervalue: 'string',
        title: 'Membership',
        filter:'text',
    },
    {
        field: 'product',
        filtervalue: 'string',
        title: 'Product',
        filter:'text',
    },
    {
        field: 'city',
        filtervalue: '',
        title: 'City',
        filter:'text',
    },
    {
        field: 'content',
        filtervalue: '',
        title: 'Content target',
        filter:'text',
    },
    {
        field: 'delivered',
        filtervalue: 'string',
        title: 'Delivered',
        filter:'text',
    },
    {
        field: 'reached',
        filtervalue: 'string',
        title: 'Reached',
        filter:'text',
    },
    {
        field: 'engaged',
        filtervalue: 'string',
        title: 'Engaged',
        filter:'text',
    },
    {
        field: 'conversion',
        filtervalue: 'string',
        title: 'Conversion',
        filter:'text',
    },
];
const gridData = [
    {
        userId: 1,
        membership: 'Platinum',
        product: 'Mutual fund',
        city: 'Washington',
        content: 'Content target 1',
        delivered: 4570,
        reached: 686,
        engaged: 320,
        conversion: 138,
    },
    {
        userId: 2,
        membership: 'Prime',
        product: 'Credit card',
        city: 'Nevada',
        content: 'Content target 2',
        delivered: 3570,
        reached: 336,
        engaged: 250,
        conversion: 108,
    },
    {
        userId: 3,
        membership: 'Gold',
        product: 'Fixed deposit',
        city: 'Hawaai',
        content: 'Content target 3',
        delivered: 3560,
        reached: 534,
        engaged: 250,
        conversion: 107,
    },
    {
        userId: 4,
        membership: 'Prime',
        product: 'Loans',
        city: 'Colorado',
        content: 'Content target 4',
        delivered: 3456,
        reached: 518,
        engaged: 242,
        conversion: 103,
    },
    {
        userId: 5,
        membership: 'Platinum',
        product: 'Personal loan',
        city: 'California',
        content: 'Content target 5',
        delivered: 2456,
        reached: 368,
        engaged: 172,
        conversion: 74,
    },
    {
        userId: 6,
        membership: 'Silver',
        product: 'Loan',
        city: 'California',
        content: 'Content target 6',
        delivered: 2656,
        reached: 369,
        engaged: 152,
        conversion: 84,
    },
];

export { gridData, gridColumnData };
