const initialState = {
    channelTypes: [],
    analyticsTypes: [],
    primarygoal: '',
    startdate: new Date().toLocaleDateString(),
    enddate: new Date().toLocaleDateString(),
    communicationName: '',
    testcampaign: '',
    productType: '',
    productCategory: '',
    primarygoalPercentage: '',
    primaryGoalType: '',
    secondaryGoal: '',
    secondarygoalPercentage: '',
    roi: false,
    dynamicList: '',
    timezone: '',
    daylightSavings: false,
    isSaved: false,
    channelOptions: [],
    analyticsOptions: [],
    tags: [],
    communicationReference: {},
    communicationReferenceConfigs: [],
    isCommunicationName: false,
    communicationOptions: {},
    dynamicListData: [],
    communicationTypes: [],
    planDropdownsFetchedFor: null,
    communicationPlanFailureApiErrors: [],
    savedChannelsId: {},
    savedChannelStatusId: [],
    channelAudiences: {},
    campaignBlastDetails: null,
    exisingLinks: {}
};

export default initialState;
