export const SUBSCRIPTION_INVOICE_GRID = [
    {
        clientId: 16,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-11-23T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0016/22-23',
        salePrice: 4800.0,
        listPrice: 4800.0,
        pricePerMonth: 0,
        dueDate: '2023-12-28T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '3',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 17,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-11-23T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0046/22-23',
        salePrice: 4250.0,
        listPrice: 4250.0,
        pricePerMonth: 0,
        dueDate: '2023-08-15T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Not paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 18,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-12-14T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0011/22-23',
        salePrice: 5200.0,
        listPrice: 5200.0,
        pricePerMonth: 0,
        dueDate: '2023-01-12T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 19,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-08-22T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0041/22-23',
        salePrice: 6980.0,
        listPrice: 6980.0,
        pricePerMonth: 0,
        dueDate: '2022-08-02T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 20,
        address1: null,
        address2: null,
        invoiceDateTime: '2021-09-22T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0041/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2021-12-02T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 18,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-12-14T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0011/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2023-01-12T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 19,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-08-22T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0041/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2022-08-02T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Not paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 16,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-11-23T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0016/22-23',
        salePrice: 4800.0,
        listPrice: 4800.0,
        pricePerMonth: 0,
        dueDate: '2023-12-28T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 17,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-11-23T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0046/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2023-08-15T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Not paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 18,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-12-14T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0011/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2023-01-12T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 19,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-08-22T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0041/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2022-08-02T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Not paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 20,
        address1: null,
        address2: null,
        invoiceDateTime: '2021-09-22T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0041/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2021-12-02T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Not paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 18,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-12-14T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0011/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2023-01-12T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
    {
        clientId: 19,
        address1: null,
        address2: null,
        invoiceDateTime: '2022-08-22T11:54:34',
        invoiceId: 8,
        invoiceNo: '000008-0041/22-23',
        salePrice: 3999.0,
        listPrice: 3999.0,
        pricePerMonth: 0,
        dueDate: '2022-08-02T12:25:45',
        customerName: 'Resulticks',
        accountNo: 'INE-UmVRes-15',
        accountType: null,
        transactionNo: '0',
        description: null,
        monthlyCharge: 0,
        paymentFrequecy: '4',
        paymentFrequecyDescription: null,
        paymentModeId: 1,
        paymentMode: 'Credit Card',
        statusId: 1,
        status: 'Not paid',
        totalAmount: 0,
        discountFrequency: 0,
        discountamt: 0.0,
        taxAmount: 0,
        authorizationCode: null,
        emailId: null,
        maskedEmailId: null,
        paymentAmount: null,
        city: null,
        country: null,
        clientName: null,
    },
];
