export const DDL_RECENT_DATA = ['Recent communications', 'Recently completed communications'];

export const NO_DATA_RECENT = [
    [
        {
            campaignName: '',
            performanceScore: 0,
            status: 'Warming Up',
            startDate: '',
            endDate: '',
            targetInfo: '',
            channelInfo: '',
            completion: '0.0',
            primaryTarget: '0.0',
        },
        {
            campaignName: '',
            performanceScore: 0,
            status: 'Warming Up',
            startDate: '',
            endDate: '',
            targetInfo: '',
            channelInfo: '',
            completion: '0.0',
            primaryTarget: '0.0',
        },
        {
            campaignName: '',
            performanceScore: 0,
            status: 'Warming Up',
            startDate: '',
            endDate: '',
            targetInfo: '',
            channelInfo: '',
            completion: '0.0',
            primaryTarget: '0.0',
        },
    ],
    // [
    //     {
    //         campaignName: 'ZERODAY PLA2A TOP3 EM R26 31JUL23',
    //         performanceScore: 0,
    //         status: 'Warming Up',
    //         startDate: 'Mon, 2023 Jul, 31',
    //         endDate: 'Thu, 2023 Aug, 03',
    //         targetInfo: 'Conversion',
    //         channelInfo: 'Email,WebAnalytics,Mobile',
    //         completion: '0.0',
    //         primaryTarget: '0.5',
    //     },
    //     {
    //         campaignName: 'ZERODAY_AL_TOPUP_J5_FRESH M1_31JUL',
    //         performanceScore: 0,
    //         status: 'Warming Up',
    //         startDate: 'Mon, 2023 Jul, 31',
    //         endDate: 'Thu, 2023 Aug, 03',
    //         targetInfo: 'Conversion',
    //         channelInfo: 'Mobile,WebAnalytics',
    //         completion: '0.0',
    //         primaryTarget: '0.05',
    //     },
    //     {
    //         campaignName: 'ZERODAY_AL_TOPUP_J5_FRESH_M0_31JUL',
    //         performanceScore: 0,
    //         status: 'Warming Up',
    //         startDate: 'Mon, 2023 Jul, 31',
    //         endDate: 'Thu, 2023 Aug, 03',
    //         targetInfo: 'Conversion',
    //         channelInfo: 'Mobile,WebAnalytics',
    //         completion: '0.0',
    //         primaryTarget: '0.05',
    //     },
    // ],
];
