import { getUserDetails } from 'Utils/modules/crypto';
import { form_generator_large, goals_benchmark_large, offer_management_large, pre_account_setting_large, pre_alert_notification_large, pre_audience_score_large, pre_budget_planning_large, pre_communication_settings_large, pre_companies_large, pre_consumptions_large, pre_data_catalogue_large, pre_data_exchange_large, pre_invoice_large, pre_license_info_large, pre_my_profile_large, pre_payment_settings_large, pre_roles_permission_large, pre_template_builder_large, pre_user_management_large } from 'Constants/GlobalConstant/Glyphicons';
const { licenseTypeId, isAgency, isEnterprisePlus } = getUserDetails();
let enableCompanies = false;
if (licenseTypeId === '3' && isAgency === true) enableCompanies = true;
else if (licenseTypeId === '3' && isAgency === false) enableCompanies = true;
// console.log('licenseTypeId:pref ', licenseTypeId);
// console.log('enableCompanies:pref ', enableCompanies);
export const PREFRENCE_LISTS = [
    {
        title: 'General',
        lists: [
            {
                featureId: 8,
                icon: `${pre_my_profile_large}`,
                title: 'My profile',
                link: 'my-profile',
                tooltip: 'Update and manage your profile',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Myprofile',
            },
            {
                featureId: 9,
                icon: `${pre_account_setting_large}`,
                title: 'Account settings',
                link: 'account-settings',
                tooltip: 'Update and manage your account settings',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Accountsettings',
            },
            {
                featureId: 12,
                icon: `${pre_user_management_large}`,
                title: 'User management',
                link: 'users',
                tooltip: 'Add, modify, and remove users',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Usermanagement',
            },
            {
                featureId: 10,
                icon: `${pre_roles_permission_large}`,
                title: 'User roles',
                link: 'roles-and-permissions',
                tooltip: 'Assign and customize user roles and permissions',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Userroles',
            },
            {
                featureId: 11,
                icon: `${pre_companies_large}`,
                title: !isAgency ? 'Companies' : 'Clients',
                link: 'company-list',
                tooltip: `Manage ${isAgency ? 'clients' : 'companies'} in your account`,
                indicate: false,
                disable: (licenseTypeId === '3' && isEnterprisePlus === true) || isAgency === true ? false : true, //!enableCompanies,
                id: 'rs_PREFRENCE_LISTS_companylist',
                //disable: false,
            },
            {
                featureId: 19,
                icon: `${pre_alert_notification_large}`,
                title: 'Alerts',
                link: 'alerts-and-notifications',
                tooltip: 'Manage your alerts and notifications',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Alerts',
            },
        ],
    },
    {
        title: 'Setup',
        lists: [
            {
                featureId: 15,
                icon: `${pre_communication_settings_large}`,
                title: 'Communication settings',
                link: 'communication-settings',
                tooltip: 'Customize and manage your communication settings',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_commu.settings',
            },
            // {
            //     featureId: 13,
            //     icon: `${goals_benchmark_large}`,
            //     title: 'Goals & benchmark',
            //     link: 'goals-and-benchmark',
            //     tooltip: 'Set, update and manage benchmarks for all channels',
            //     indicate: false,
            //     disable: false,
            // },
            {
                featureId: 51,
                icon: `${offer_management_large}`,
                title: 'Offer management',
                link: 'offer-management',
                tooltip: 'Create static and dynamic offers',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Offermanagement',
            },
            {
                featureId: 16,
                icon: `${pre_template_builder_large}`,
                title: 'Template builder',
                link: 'template-gallery',
                tooltip: 'Create and manage templates',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_TemplateBuilder',
            },
            {
                featureId: 52,
                icon: `${pre_audience_score_large}`,
                title: 'Audience score',
                link: 'audience-score',
                tooltip: 'Configure your audience scoring criteria',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_AudienceScore',
            },
            {
                featureId: 53,
                icon: `${pre_data_catalogue_large}`,
                title: 'Data catalog',
                link: 'data-catalogue',
                tooltip: 'View and categorize data attributes',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_DataCatalogue',
            },
            // {
            //     featureId: 16,
            //     icon: `${form_generator_large}`,
            //     title: 'Form builder',
            //     link: 'form-generator',
            //     tooltip: 'Create new forms for your digital properties',
            //     indicate: false,
            //     disable: false,
            // },
            {
                featureId: 44,
                icon: `${pre_data_exchange_large}`,
                title: 'Data exchange',
                link: 'data-exchange',
                tooltip: 'Connect to various data sources and systems',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_DataExchange',
            },
        ],
    },
    {
        title: 'Billing',
        lists: [
            {
                featureId: 0,
                icon: `${pre_budget_planning_large}`,
                title: 'Budget & planning',
                link: 'budget-and-planning',
                tooltip: 'Set and manage budget',
                indicate: false,
                disable: true,
                id: 'rs_PREFRENCE_LISTS_Budget&Planning',
            },
            {
                featureId: 33,
                icon: `${pre_consumptions_large}`,
                title: 'Consumptions',
                link: 'consumptions',
                tooltip: 'View channel bandwidth and consumption',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Consumptions',
            },
            {
                featureId: 54,
                icon: `${pre_invoice_large}`,
                title: 'Invoices',
                link: 'invoice-list',
                tooltip: 'View and download platform invoices',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_Invoices',
            },
            {
                featureId: 0,
                icon: `${pre_payment_settings_large}`,
                title: 'Payment settings',
                link: 'payment-settings',
                tooltip: 'Set and manage payment modes',
                indicate: false,
                disable: true,
                id: 'rs_PREFRENCE_LISTS_PaymentSettings',
            },
            {
                featureId: 54,
                icon: `${pre_license_info_large}`,
                title: 'License info',
                link: 'license-info',
                tooltip: 'View and upgrade your current subscription plan',
                indicate: false,
                disable: false,
                id: 'rs_PREFRENCE_LISTS_LicenseInfo',
            },
        ],
    },
];

export const businessTypesList = [
    {
        titleId: 1,
        title: 'GHQ',
    },
    {
        titleId: 2,
        title: 'RHQ',
    },
    {
        titleId: 3,
        title: 'LOC',
    },
];
