export const buildPayload = ({ formState, payloadData }) => {
    const { mode, securityId } = payloadData;
    const { roleName } = formState;
    const tempRoles = { ...formState };
    delete tempRoles.roleName;
    delete tempRoles.statusAll;

    return {
        securityGroupID: mode === 'new' ? 0 : securityId,
        securityGroupName: roleName.trim(),
        SGroupFeature: formState.permissions.map((permission) => {
            const [create, read, update, deleteAccess] = permission.values;
            return {
                viewAccess: read.status,
                addAccess: create.status,
                updateAccess: update.status,
                deleteAccess: deleteAccess.status,
                featureID: permission.featureID,
            };
        }),
    };
};

export const permissions = [
    {
        featureId: 1,
        featureName: 'Dashboard',
        viewAccess: true,
        addAccess: false,
        updateAccess: false,
        deleteAccess: false,
    },
    {
        featureId: 3,
        featureName: 'Communications',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: true,
    },
    {
        featureId: 4,
        featureName: 'Analytics',
        viewAccess: true,
        addAccess: false,
        updateAccess: false,
        deleteAccess: false,
    },
    {
        featureId: 8,
        featureName: 'My profile',
        viewAccess: true,
        addAccess: false,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 9,
        featureName: 'Account settings',
        viewAccess: true,
        addAccess: false,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 10,
        featureName: 'Roles & permissions',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: true,
    },
    {
        featureId: 11,
        featureName: 'Companies/Clients',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 12,
        featureName: 'Users',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: true,
    },
    {
        featureId: 13,
        featureName: 'Goals & benchmark',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 15,
        featureName: 'Communication settings',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 16,
        featureName: 'Form generator',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 19,
        featureName: 'Alerts & notifications',
        viewAccess: true,
        addAccess: false,
        updateAccess: false,
        deleteAccess: false,
    },
    {
        featureId: 26,
        featureName: 'Audit log report',
        viewAccess: true,
        addAccess: false,
        updateAccess: false,
        deleteAccess: false,
    },
    {
        featureId: 29,
        featureName: 'Audience analytics 360',
        viewAccess: true,
        addAccess: false,
        updateAccess: false,
        deleteAccess: false,
    },
    {
        featureId: 33,
        featureName: 'Consumptions',
        viewAccess: true,
        addAccess: false,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 44,
        featureName: 'Data exchange',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 45,
        featureName: 'Audience score',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {   featureId: 46,
        featureName: "Data attributes log",
        addAccess: false,
        deleteAccess: false, 
        updateAccess: true,
        viewAccess: true,
    },
    {
        featureId: 47,
        featureName: 'Add Audience Via Manual upload, CSV, XML',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 48,
        featureName: 'Add Audience Via remote data source or SFTP-FTP',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 49,
        featureName: 'Audience - Target Lists',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 50,
        featureName: 'Audience - Dynamic Lists',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 51,
        featureName: 'Offer Management',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 52,
        featureName: 'Lead Score',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 53,
        featureName: 'Data Attributes',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {
        featureId: 54,
        featureName: 'Budget & Planning',
        viewAccess: true,
        addAccess: true,
        updateAccess: true,
        deleteAccess: false,
    },
    {   featureId: 55,
        featureName: "SFTP-FTP",
        addAccess: false,
        deleteAccess: false,
        updateAccess: true,
        viewAccess: true
    }
];

