import { email_large, messaging_rcs_large, mobile_analytics_large, mobile_notification_large, mobile_sms_large, qrcode_large, social_digipop_large, social_facebook_app_large, social_facebook_large, social_google_ad_large, social_google_plus_large, social_instagram_large, social_linkedin_ads_large, social_linkedin_large, social_pinterest_large, social_twitter_ads_large, social_twitter_large, social_whatsapp_large, web_analytics_large, web_notification_large, webinar_large } from 'Constants/GlobalConstant/Glyphicons';
export const GOALS_SUMMARY = [
    {
        channelName: 'Email',
        iconName: email_large,
        reach: 'Opens, Forwards',
        engagement: 'Clicks, Clicks from forwarded mail',
        conversion: 'Participation, Registration, Registration from forwarded mails',
    },
    {
        channelName: 'SMS',
        iconName: mobile_sms_large,
        reach: 'Delivered',
        engagement: 'Reply, URL clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'WhatsApp',
        iconName: social_whatsapp_large,
        reach: 'Messages sent, Messages delivered',
        engagement: 'Message opens(Read Receipts),Replies,Button clicks(CTA clicks),URL clicks',
        conversion: 'Participation, Registration,Form submission,Purchase / Transaction',
    },
    {
        channelName: 'RCS',
        iconName: messaging_rcs_large,
        reach: 'Delivered, Seen',
        engagement: 'URL clicks, Suggested replies, Media views, Button clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Mobile push',
        iconName: mobile_notification_large,
        reach: 'Delivered',
        engagement: 'URL clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Web push',
        iconName: web_notification_large,
        reach: 'Delivered',
        engagement: 'Link clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'QR code',
        iconName: qrcode_large,
        reach: 'Scan',
        engagement: 'Landing page, Link clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Facebook app',
        iconName: social_facebook_app_large,
        reach: 'Daily unique canvas visitors, Friends of fan',
        engagement: 'Shares, Likes',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Facebook',
        iconName: social_facebook_large,
        reach: 'Page likes',
        engagement: 'Shares, Likes, Comments, Responding to event, Answering a question, Clicks on post',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Facebook ads',
        iconName: social_facebook_app_large,
        reach: 'Impressions',
        engagement: 'Shares, Likes, Comments, Clicks on post',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'X',
        iconName: social_twitter_large,
        reach: 'Account followers',
        engagement: 'Like, Retweet, Reply',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'X ads',
        iconName: social_twitter_ads_large,
        reach: 'Impressions',
        engagement: 'Like, Retweet, Link clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Digipop',
        iconName: social_digipop_large,
        reach: 'Impressions',
        engagement: 'Like, Retweet, Link clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'LinkedIn',
        iconName: social_linkedin_large,
        reach: 'Account followers',
        engagement: 'Shares, Likes, Comments, Participating in a discussion, Clicks on post',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'LinkedIn ads',
        iconName: social_linkedin_ads_large,
        reach: 'Impressions',
        engagement: 'Shares, Likes, Comments, Clicks on post',
        conversion: 'Participation, Registration',
    },
    // {
    //     channelName: 'Google+',
    //     iconName: social_google_plus_large,
    //     reach: 'Page +1s',
    //     engagement: 'Post +1s, Reshares, Comments',
    //     conversion: 'Participation, Registration',
    // },
    {
        channelName: 'Google ads',
        iconName: social_google_ad_large,
        reach: 'Impressions',
        engagement: 'Link clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Instagram',
        iconName: social_instagram_large,
        reach: 'Business account followers',
        engagement: 'Likes, Replies, Shares, Sends',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Pinterest',
        iconName: social_pinterest_large,
        reach: 'Account followers',
        engagement: 'Likes, Comments, Shares, Sends',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Webinar',
        iconName: webinar_large,
        reach: 'Registration',
        engagement: 'Participation',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'Web analytics',
        iconName: web_analytics_large,
        reach: 'Session',
        engagement: 'Link clicks',
        conversion: 'Participation, Registration',
    },
    {
        channelName: 'App analytics',
        iconName: mobile_analytics_large,
        reach: 'Session',
        engagement: 'Link clicks',
        conversion: 'Participation, Registration',
    },
];
