/** Grid column / action labels — no Placeholders barrel import (prod TDZ). */
export const AUDIENCE_GRID_LABELS = Object.freeze({
    TABLE_LIST_NAME: 'List name',
    CREATED_BY: 'Created by',
    CREATED_ON: 'Created on',
    COMMUNICATION_SEND: 'Commu. sent',
    ACTION: 'Action',
    ACTIONS: 'Actions',
    EDIT: 'Edit',
    INFO: 'Info',
    VIEW: 'View',
    MORE: 'More',
    PENDING_FOR_APPROVAL: 'Pending for approval',
    REQUEST_APPROVED: 'Request approved',
    REQUEST_REJECTED: 'Request rejected',
    LIST_APPROVAL_PENDING: 'List approval pending',
    LIST_APPROVED: 'List approved',
    LIST_REJECTED: 'List rejected',
    REMOVE_LIST: 'Remove list',
    AVERAGE_PROJECTED_REACH_RATE: 'Average/Projected reach rate',
    SEG_AUDIENCE: 'Seg. audience',
    ARCHIVE: 'Archive',
    UNARCHIVE: 'Unarchive',
    DOWNLOADSHARE: 'Download/Share',
    DATA_AUGMENTATION: 'Data augmentation',
});
