/**
 * Icon class strings for the audience chunk — no Glyphicons barrel import (prod TDZ).
 */
export const AUDIENCE_GLYPH = Object.freeze({
    arrow_left_medium: 'icon-rs-arrow-left-medium',
    arrow_right_medium: 'icon-rs-arrow-right-medium',
    in_between_medium: 'icon-rs-in-between-medium',
    equal_to_attribute_medium: 'icon-rs-equal-to-attribute-medium',
    equal_to_medium: 'icon-rs-equal-to-medium',
    greater_than_attribute_medium: 'icon-rs-greater-than-attribute-medium',
    lesser_than_attribute_medium: 'icon-rs-lesser-than-attribute-medium',
    minus_medium: 'icon-rs-minus-medium',
    not_equal_to_attribute_medium: 'icon-rs-not-equal-to-attribute-medium',
    not_equal_to_medium: 'icon-rs-not-equal-to-medium',
    plus_medium: 'icon-rs-plus-medium',
    circle_arrow_down_medium: 'icon-rs-circle-arrow-down-medium',
    circle_arrow_right_mini: 'icon-rs-circle-arrow-right-mini',
    circle_arrow_right_medium: 'icon-rs-circle-arrow-right-medium',
    alert_medium: 'icon-rs-alert-medium',
    circle_info_medium: 'icon-rs-circle-info-medium',
    circle_pencil_medium: 'icon-rs-circle-pencil-medium',
    delete_medium: 'icon-rs-delete-medium',
    eye_medium: 'icon-rs-eye-medium',
    user_medium: 'icon-rs-user-medium',
    user_pending_medium: 'icon-rs-user-pending-medium',
    user_reject_medium: 'icon-rs-user-reject-medium',
    user_tick_medium: 'icon-rs-user-tick-medium',
    settings_large: 'icon-rs-settings-large',
    settings_medium: 'icon-rs-settings-medium',
    user_star_medium: 'icon-rs-user-star-medium',
    key_fill_mini: 'icon-rs-key-fill-mini',
    email_medium: 'icon-rs-email-medium',
    mobile_sms_medium: 'icon-rs-mobile-sms-medium',
    zip_medium: 'icon-rs-zip-medium',
    social_facebook_medium: 'icon-rs-social-facebook-medium',
    dollar_medium: 'icon-rs-dollar-medium',
    age_medium: 'icon-rs-age-medium',
    social_instagram_medium: 'icon-rs-social-instagram-medium',
    social_twitter_medium: 'icon-rs-social-twitter-medium',
    mobile_notification_medium: 'icon-rs-mobile-notification-medium',
    web_notification_medium: 'icon-rs-web-notification-medium',
    custom_attributes_large: 'icon-rs-custom-attributes-large',
});
