export const personaGrid = {
    status: true,
    statusCode: 200,
    message: 'Success',
    totalListCount: 61,
    data: [
        {
            personaListID: 65,
            personaListName: 'Young professionals',
            createdDate: '2023-03-23T08:00:00',
            createdBy: 'Admin',
            categoryTitle1: 'Loan type',
            categoryTitle2: 'Account type',
            categoryTitle3: 'Age',
            categoryTitle4: 'Income',
            categoryDesc1: 'Home loan',
            categoryDesc2: 'Salary account',
            categoryDesc3: '35 to 45 years',
            categoryDesc4: '$3,000 to $3,500',
        },
        {
            personaListID: 66,
            personaListName: 'Foodie',
            createdDate: '2023-03-23T08:00:00',
            createdBy: 'Admin',
            categoryTitle1: 'Purchase category',
            categoryTitle2: 'Purchase frequency',
            categoryTitle3: 'Spend worth',
            categoryTitle4: 'Interests',
            categoryDesc1: 'Restaurant',
            categoryDesc2: '4 times in a month',
            categoryDesc3: 'Above $4,000',
            categoryDesc4: 'Food',
        },
        {
            personaListID: 67,
            personaListName: 'Travel',
            createdDate: '2023-03-23T08:00:00',
            createdBy: 'Admin',
            categoryTitle1: 'Travel category',
            categoryTitle2: 'Travel frequency',
            categoryTitle3: 'Spend worth',
            categoryTitle4: 'Interests',
            categoryDesc1: 'Economy',
            categoryDesc2: '3 times in a year',
            categoryDesc3: 'Above $15,000',
            categoryDesc4: 'Nature',
        },
    ],
};
