import {
    afternoonColor,
    androidColor,
    blueColor,
    blueLightColor,
    ch_ad_hoc_list,
    ch_age,
    ch_alert,
    ch_all_audience,
    ch_auto_cluster,
    ch_body_bg_color,
    ch_call_center,
    ch_color1,
    ch_color2,
    ch_color3,
    ch_color4,
    ch_color5,
    ch_color6,
    ch_color7,
    ch_color8,
    ch_color9,
    ch_completed,
    ch_country,
    ch_dark_blue,
    ch_dark_blue_green,
    ch_dark_green,
    ch_dark_grey,
    ch_dark_orange,
    ch_dark_pink,
    ch_dark_purple,
    ch_dark_red,
    ch_dark_yellow,
    ch_direct_mail,
    ch_draft,
    ch_dynamic_audience,
    ch_email,
    ch_facebook,
    ch_female,
    ch_friday,
    ch_gender,
    ch_google_plus,
    ch_head_band_color,
    ch_heavy_dark_blue,
    ch_heavy_dark_red,
    ch_identifiedColor,
    ch_inprogress,
    ch_insta,
    ch_knownColor,
    ch_light_blue,
    ch_light_blue_green,
    ch_light_green,
    ch_light_grey,
    ch_light_orange,
    ch_light_pink,
    ch_light_purple,
    ch_light_red,
    ch_light_yellow,
    ch_linkedIn,
    ch_list_audience,
    ch_male,
    ch_match_list,
    ch_medium_blue,
    ch_medium_blue_green,
    ch_medium_green,
    ch_medium_grey,
    ch_medium_orange,
    ch_medium_pink,
    ch_medium_purple,
    ch_medium_red,
    ch_medium_yellow,
    ch_mobile_push,
    ch_monday,
    ch_multi_status,
    ch_negative,
    ch_neutral,
    ch_notifications,
    ch_others,
    ch_paid_media,
    ch_pinterest,
    ch_positive,
    ch_primary_black,
    ch_primary_blue,
    ch_primary_btn,
    ch_primary_btn_hover,
    ch_primary_green,
    ch_primary_grey,
    ch_primary_orange,
    ch_primary_red,
    ch_qR_code,
    ch_quaternary_blue,
    ch_quaternary_grey,
    ch_quaternary_orange,
    ch_rcs,
    ch_saturday,
    ch_scheduled,
    ch_secondary_black,
    ch_secondary_blue,
    ch_secondary_grey,
    ch_secondary_orange,
    ch_secondary_red,
    ch_seed_list,
    ch_sms,
    ch_sunday,
    ch_suppression,
    ch_tertiary_blue,
    ch_tertiary_grey,
    ch_tertiary_orange,
    ch_thursday,
    ch_tuesday,
    ch_twitter,
    ch_unKnownColor,
    ch_vms,
    ch_web_push,
    ch_website,
    ch_wednesday,
    ch_whatsapp,
    ch_zip_code,
    cyanColor,
    earlyMorningColor,
    englishColor,
    eveningColor,
    fullyConversedColor,
    googlePlaystoreColor,
    greenColor,
    greenLightColor,
    greyDarkColor,
    greyLightColor,
    iosColor,
    macColor,
    morningColor,
    nightColor,
    orangeColor,
    othersColor,
    spanishColor,
    televisionColor,
    windowsColor,
    yellowColor,
    youtubeWatchpageColor
} from 'Constants/GlobalConstant/Colors/colorsVariable';

export const commonColors = [
    {
        color: ch_body_bg_color,
        name: 'BG color',
        type: 'Background color',
        classColor: 'body-bg-color',
        js: 'ch_body_bg_color',
        scss: 'body-bg-color',
    },
    {
        color: ch_head_band_color,
        name: 'Head Band',
        type: '',
        classColor: 'head-band-color',
        js: 'ch_head_band_color',
        scss: 'head-band-color',
    },
    {
        color: ch_primary_blue,
        name: 'Primary blue color',
        type: 'Main Heading, icons, save btn',
        classColor: 'primary-blue',
        js: 'ch_primary_blue',
        scss: 'primary-blue',
    },
    {
        color: ch_secondary_blue,
        name: 'Secondary blue color',
        type: 'Tab, border-top line, text box active lines',
        classColor: 'secondary-blue',
        js: 'ch_secondary_blue',
        scss: 'secondary_blue',
    },
    {
        color: ch_tertiary_blue,
        name: 'Tertiary blue color',
        type: 'Tab, border-top line, text box active lines, Odd/Even bg color',
        classColor: 'tertiary-blue',
        js: 'ch_tertiary_blue',
        scss: 'tertiary-blue',
    },
    {
        color: ch_quaternary_blue,
        name: 'Quaternary color',
        type: 'Portlet border color',
        classColor: 'quaternary-blue',
        js: 'ch_quaternary_blue',
        scss: 'quaternary-blue',
    },
    {
        color: ch_primary_black,
        name: 'Primary black',
        type: 'Heading text',
        classColor: 'primary-black',
        js: 'ch_primary_black',
        scss: 'primary-black',
    },
    {
        color: ch_secondary_black,
        name: 'Secondry black',
        type: 'Sub heading text',
        classColor: 'secondary-black',
        js: 'ch_secondary_black',
        scss: 'secondary-black',
    },
    {
        color: ch_primary_grey,
        name: 'Primary grey',
        type: 'Place holder, grey text',
        classColor: 'primary-grey',
        js: 'ch_primary_grey',
        scss: 'primary-grey',
    },
    {
        color: ch_secondary_grey,
        name: 'Secondary grey',
        type: 'Texbox line, check box, Bg fill',
        classColor: 'secondary-grey',
        js: 'ch_secondary_grey',
        scss: 'secondary-grey',
    },
    {
        color: ch_tertiary_grey,
        name: 'Tertiary grey',
        type: 'Breadcrumbs, tab, section lines',
        classColor: 'tertiary-grey',
        js: 'ch_tertiary_grey',
        scss: 'tertiary-grey',
    },
    {
        color: ch_quaternary_grey,
        name: 'Quaternary grey',
        type: 'Inactive bg',
        classColor: 'quaternary-grey',
        js: 'ch_quaternary_grey',
        scss: 'quaternary-grey',
    },
    {
        color: ch_primary_green,
        name: 'Green',
        type: 'Active, confirmation color',
        classColor: 'primary-green',
        js: 'ch_primary_green',
        scss: 'primary-green',
    },
    {
        color: ch_primary_orange,
        name: 'Primary orange',
        type: 'Cancel btn, Engagement bg',
        classColor: 'primary-orange',
        js: 'ch_primary_orange',
        scss: 'primary-orange',
    },
    {
        color: ch_secondary_orange,
        name: 'Secondary orange',
        type: 'Crown icon color',
        classColor: 'secondary-orange',
        js: 'ch_secondary_orange',
        scss: 'secondary-orange',
    },
    {
        color: ch_tertiary_orange,
        name: 'Tertiary orange',
        type: 'Logo thunder',
        classColor: 'tertiary-orange',
        js: 'ch_tertiary_orange',
        scss: 'tertiary-orange',
    },
    {
        color: ch_quaternary_orange,
        name: 'Quaternary orange',
        type: 'Menu active',
        classColor: 'Quaternary-orange',
        js: 'ch_quaternary_orange',
        scss: 'quaternary-orange',
    },
    {
        color: ch_primary_btn,
        name: 'Submit btn',
        type: '',
        classColor: '',
        js: 'ch_primary_btn',
        scss: 'primary-btn',
    },
    {
        color: ch_primary_btn_hover,
        name: 'Submit btn hover',
        type: '',
        classColor: '',
        js: 'ch_primary_btn_hover',
        scss: 'primary-btn-hover',
    },
    {
        color: ch_primary_red,
        name: 'Remove',
        type: '',
        classColor: 'primary-red',
        js: 'ch_primary_red',
        scss: 'primary-red',
    },
    {
        color: ch_secondary_red,
        name: 'Secondary red',
        type: 'Exclusion bg color',
        classColor: 'secondary-red',
        js: 'ch_secondary_red',
        scss: 'secondary-red',
    },
];

export const solidBlueColors = [
    {
        color: ch_heavy_dark_blue,
        name: 'Heavy dark',
        type: '',
        js: 'ch_heavy_dark_blue',
        scss: 'blue-heavy',
        classColor: 'blue-heavy-dark',
    },
    { color: ch_dark_blue, name: 'Dark', type: '', js: 'ch_dark_blue', scss: 'blue-dark', classColor: 'blue-dark' },
    {
        color: ch_medium_blue,
        name: 'Medium',
        type: '',
        js: 'ch_medium_blue',
        scss: 'blue-medium',
        classColor: 'blue-medium',
    },
    {
        color: ch_light_blue,
        name: 'Light',
        type: '',
        js: 'ch_light_blue',
        scss: 'blue-light',
        classColor: 'blue-light',
    },
];
export const solidGreenColors = [
    {
        color: ch_dark_green,
        name: 'Dark',
        type: '',
        js: 'ch_dark_green',
        scss: 'green-dark',
        classColor: 'green-dark',
    },
    {
        color: ch_medium_green,
        name: 'Medium',
        type: '',
        js: 'ch_medium_green',
        scss: 'green-medium',
        classColor: 'green-medium',
    },
    {
        color: ch_light_green,
        name: 'Light',
        type: '',
        js: 'ch_light_green',
        scss: 'green-light',
        classColor: 'green-light',
    },
];
export const solidOrangeColors = [
    {
        color: ch_dark_orange,
        name: 'Dark',
        type: '',
        js: 'ch_dark_orange',
        scss: 'orange-dark',
        classColor: 'orange-dark',
    },
    {
        color: ch_medium_orange,
        name: 'Medium',
        type: '',
        js: 'ch_medium_orange',
        scss: 'orange-medium',
        classColor: 'orange-medium',
    },
    {
        color: ch_light_orange,
        name: 'Light',
        type: '',
        js: 'ch_light_orange',
        scss: 'orange-light',
        classColor: 'orange-light',
    },
];
export const solidYellowColors = [
    {
        color: ch_dark_yellow,
        name: 'Dark',
        type: '',
        js: 'ch_dark_yellow',
        scss: 'yellow-dark',
        classColor: 'yellow-dark',
    },
    {
        color: ch_medium_yellow,
        name: 'Medium',
        type: '',
        js: 'ch_medium_yellow',
        scss: 'yellow-medium',
        classColor: 'yellow-medium',
    },
    {
        color: ch_light_yellow,
        name: 'Light',
        type: '',
        js: 'ch_light_yellow',
        scss: 'yellow-light',
        classColor: 'yellow-light',
    },
];
export const solidRedColors = [
    {
        color: ch_heavy_dark_red,
        name: 'Heavy dark',
        type: '',
        js: 'ch_heavy_dark_red',
        scss: 'red-heavy-dark',
        classColor: 'red-heavy-dark',
    },
    {
        color: ch_dark_red,
        name: 'Dark',
        type: '',
        js: 'ch_dark_red',
        scss: 'red-dark',
        classColor: 'red-dark',
    },
    {
        color: ch_medium_red,
        name: 'Medium',
        type: '',
        js: 'ch_medium_red',
        scss: 'red-medium',
        classColor: 'red-medium',
    },
    {
        color: ch_light_red,
        name: 'Light',
        type: '',
        js: 'ch_light_red',
        scss: 'red-light',
        classColor: 'red-light',
    },
];
export const solidBlueGreenColors = [
    {
        color: ch_dark_blue_green,
        name: 'Dark',
        type: '',
        js: 'ch_dark_blue_green',
        scss: 'blue-green-dark',
        classColor: 'green-dark-blue',
    },
    {
        color: ch_medium_blue_green,
        name: 'Medium',
        type: '',
        js: 'ch_medium_blue_green',
        scss: 'blue-green-medium',
        classColor: 'green-medium-blue',
    },
    {
        color: ch_light_blue_green,
        name: 'Light',
        type: '',
        js: 'ch_light_blue_green',
        scss: 'blue-green-light',
        classColor: 'green-light-blue',
    },
];
export const solidGreyColors = [
    {
        color: ch_dark_grey,
        name: 'Dark',
        type: '',
        js: 'ch_dark_grey',
        scss: 'grey-dark',
        classColor: 'grey-dark',
    },
    {
        color: ch_medium_grey,
        name: 'Medium',
        type: '',
        js: 'ch_medium_grey',
        scss: 'grey-medium',
        classColor: 'grey-medium',
    },
    {
        color: ch_light_grey,
        name: 'Light',
        type: '',
        js: 'ch_light_grey',
        scss: 'grey-light',
        classColor: 'grey-light',
    },
];
export const solidPinkColors = [
    {
        color: ch_dark_pink,
        name: 'Dark',
        type: '',
        js: 'ch_dark_pink',
        scss: 'pink-dark',
        classColor: 'pink-dark',
    },
    {
        color: ch_medium_pink,
        name: 'Medium',
        type: '',
        js: 'ch_medium_pink',
        scss: 'pink-medium',
        classColor: 'pink-medium',
    },
    {
        color: ch_light_pink,
        name: 'Light',
        type: '',
        js: 'ch_light_pink',
        scss: 'pink-light',
        classColor: 'pink-light',
    },
];
export const solidPurpleColors = [
    {
        color: ch_dark_purple,
        name: 'Dark',
        type: '',
        js: 'ch_dark_purple',
        scss: 'purple-dark',
        classColor: 'purple-dark',
    },
    {
        color: ch_medium_purple,
        name: 'Medium',
        type: '',
        js: 'ch_medium_purple',
        scss: 'purple-medium',
        classColor: 'purple-medium',
    },
    {
        color: ch_light_purple,
        name: 'Light',
        type: '',
        js: 'ch_light_purple',
        scss: 'purple-light',
        classColor: 'purple-light',
    },
];
export const communicationStatusColors = [
    { color: ch_draft, name: 'Draft', type: '', classColor: 'draft', js: 'ch_draft', scss: 'ch_draft' },
    {
        color: ch_completed,
        name: 'Completed',
        type: '',
        classColor: 'completed',
        js: 'ch_completed',
        scss: 'ch_completed',
    },
    {
        color: ch_scheduled,
        name: 'Scheduled',
        type: '',
        classColor: 'scheduled',
        js: 'ch_scheduled',
        scss: 'ch_scheduled',
    },
    {
        color: ch_inprogress,
        name: 'Inprogress',
        type: '',
        classColor: 'inprogress',
        js: 'ch_inprogress',
        scss: 'ch_inprogress',
    },
    { color: ch_alert, name: 'Alert', type: '', classColor: 'alert', js: 'ch_alert', scss: 'ch_alert' },
    {
        color: ch_multi_status,
        name: 'Multi status',
        type: '',
        classColor: 'multi-status',
        js: 'ch_multi_status',
        scss: 'ch_multi_status',
    },
];
export const languageColors = [
    { color: englishColor, name: 'English', type: '', classColor: '', js: 'englishColor', scss: 'englishColor' },
    { color: spanishColor, name: 'Spanish', type: '', classColor: '', js: 'spanishColor', scss: 'spanishColor' },
];
export const AudienceListColors = [
    {
        color: ch_all_audience,
        name: 'All audience',
        type: '',
        classColor: '',
        js: 'ch_all_audience',
        scss: 'all-audience',
    },
    { color: ch_seed_list, name: 'Seed list', type: '', classColor: '', js: 'ch_seed_list', scss: 'seed-list' },
    {
        color: ch_ad_hoc_list,
        name: 'Ad-hoc list',
        type: '',
        classColor: '',
        js: 'ch_ad_hoc_list',
        scss: 'ad-hoc-list',
    },
    { color: ch_match_list, name: 'Match list', type: '', classColor: '', js: 'ch_match_list', scss: 'match-list' },
    {
        color: ch_suppression,
        name: 'Suppression',
        type: '',
        classColor: '',
        js: 'ch_suppression',
        scss: 'suppression',
    },
    {
        color: ch_auto_cluster,
        name: 'Auto cluster',
        type: '',
        classColor: '',
        js: 'ch_auto_cluster',
        scss: 'auto-cluster',
    },
];
export const ChannelColors = [
    { color: ch_email, name: 'Email', type: '', classColor: 'email', js: 'ch_email', scss: 'ch_email' },
    { color: ch_sms, name: 'SMS', type: '', classColor: 'sms', js: 'ch_sms', scss: 'ch_sms' },
    {
        color: ch_web_push,
        name: 'Webpush',
        type: '',
        classColor: 'web-push',
        js: 'ch_web_push',
        scss: 'ch_web_push',
    },
    {
        color: ch_mobile_push,
        name: 'Mobile push',
        type: '',
        classColor: 'mobile-push',
        js: 'ch_mobile_push',
        scss: 'ch_mobile_push',
    },
    { color: ch_vms, name: 'VMS', type: '', classColor: 'vms', js: 'ch_vms', scss: 'ch_vms' },
    { color: ch_rcs, name: 'RCS', type: '', classColor: 'rcs', js: 'ch_rcs', scss: 'ch_rcs' },
    {
        color: ch_call_center,
        name: 'Call center',
        type: '',
        classColor: 'call-center',
        js: 'ch_call_center',
        scss: 'ch_call_center',
    },
    {
        color: ch_whatsapp,
        name: 'Whatsapp',
        type: '',
        classColor: 'whatsapp',
        js: 'ch_whatsapp',
        scss: 'ch_whatsapp',
    },
    { color: ch_qR_code, name: 'QR code', type: '', classColor: 'qr-code', js: 'ch_qR_code', scss: 'ch_qR_code' },
    {
        color: ch_direct_mail,
        name: 'Direct mail',
        type: '',
        classColor: 'direct-mail',
        js: 'ch_direct_mail',
        scss: 'ch_direct_mail',
    },
    {
        color: ch_paid_media,
        name: 'Paid media',
        type: '',
        classColor: 'paid-media',
        js: 'ch_paid_media',
        scss: 'ch_paid_media',
    },
    { color: ch_twitter, name: 'X', type: '', classColor: 'twitter', js: 'ch_twitter', scss: 'ch_twitter' },
    {
        color: ch_facebook,
        name: 'Facebook',
        type: '',
        classColor: 'facebook',
        js: 'ch_facebook',
        scss: 'ch_facebook',
    },
    {
        color: ch_pinterest,
        name: 'Pinterest',
        type: '',
        classColor: 'pinterest',
        js: 'ch_pinterest',
        scss: 'ch_pinterest',
    },
    {
        color: ch_notifications,
        name: 'Notification',
        type: '',
        classColor: 'notification',
        js: 'ch_notifications',
        scss: 'ch_notifications',
    },
    {
        color: ch_linkedIn,
        name: 'LinkedIn',
        type: '',
        classColor: 'linkedIn',
        js: 'ch_linkedIn',
        scss: 'ch_linkedIn',
    },
    {
        color: ch_google_plus,
        name: 'Google plus',
        type: '',
        classColor: 'google_plus',
        js: 'ch_google_plus',
        scss: 'ch_google_plus',
    },
    { color: ch_insta, name: 'Insta', type: '', classColor: 'insta', js: 'ch_insta', scss: 'ch_insta' },
];
export const ChannelColors2 = [
    { color: ch_zip_code, name: 'Zip code', type: '', classColor: 'zip-code', js: 'ch_zip_code', scss: 'zip-code' },
    { color: ch_gender, name: 'Gender', type: '', classColor: 'gender', js: 'ch_gender', scss: 'gender' },
    { color: ch_male, name: 'Male', type: '', classColor: 'male', js: 'ch_male', scss: 'male' },
    { color: ch_female, name: 'Female', type: '', classColor: 'female', js: 'ch_female', scss: 'female' },
    { color: ch_age, name: 'Age', type: '', classColor: 'age', js: 'ch_age', scss: 'age' },
    { color: ch_country, name: 'Country', type: '', classColor: 'country', js: 'ch_country', scss: 'country' },
    { color: ch_website, name: 'Website', type: '', classColor: 'website', js: 'ch_website', scss: 'website' },
    { color: ch_others, name: 'Others', type: '', classColor: 'others', js: 'ch_others', scss: 'others' },
];
export const SourceColors = [
    {
        color: ch_list_audience,
        name: 'List audience',
        type: '',
        classColor: '',
        js: 'ch_list_audience',
        scss: 'list-audience',
    },
    {
        color: ch_dynamic_audience,
        name: 'Dynamic audience',
        type: '',
        classColor: '',
        js: 'ch_dynamic_audience',
        scss: 'dynamic-audience',
    },
];
export const sentimentColors = [
    {
        color: ch_positive,
        name: 'Positive',
        type: '',
        classColor: 'positive',
        js: 'ch_positive',
        scss: 'ch_positive',
    },
    { color: ch_neutral, name: 'Neutral', type: '', classColor: 'neutral', js: 'ch_neutral', scss: 'ch_neutral' },
    {
        color: ch_negative,
        name: 'Negative',
        type: '',
        classColor: 'negative',
        js: 'ch_negative',
        scss: 'ch_negative',
    },
];
export const weekColors = [
    { color: ch_monday, name: 'Monday', type: '', classColor: '', js: 'ch_monday', scss: 'ch_monday' },
    { color: ch_tuesday, name: 'Tueday', type: '', classColor: '', js: 'ch_tuesday', scss: 'ch_tuesday' },
    { color: ch_wednesday, name: 'Wednesday', type: '', classColor: '', js: 'ch_wednesday', scss: 'ch_wednesday' },
    { color: ch_thursday, name: 'Thursday', type: '', classColor: '', js: 'ch_thursday', scss: 'ch_thursday' },
    { color: ch_friday, name: 'Friday', type: '', classColor: '', js: 'ch_friday', scss: 'ch_friday' },
    { color: ch_saturday, name: 'Saturday', type: '', classColor: '', js: 'ch_saturday', scss: 'ch_saturday' },
    { color: ch_sunday, name: 'Sunday', type: '', classColor: '', js: 'ch_sunday', scss: 'ch_sunday' },
];
export const dayColors = [
    {
        color: earlyMorningColor,
        name: 'Early morning',
        type: '',
        classColor: '',
        js: 'earlyMorningColor',
        scss: 'earlyMorningColor',
    },
    { color: morningColor, name: 'Morning', type: '', classColor: '', js: 'morningColor', scss: 'morningColor' },
    {
        color: afternoonColor,
        name: 'Afternoon',
        type: '',
        classColor: '',
        js: 'afternoonColor',
        scss: 'afternoonColor',
    },
    { color: eveningColor, name: 'Evening', type: '', classColor: '', js: 'eveningColor', scss: 'eveningColor' },
    { color: nightColor, name: 'Night', type: '', classColor: '', js: 'nightColor', scss: 'nightColor' },
];
export const deviceColors = [
    { color: androidColor, name: 'Android', type: '', classColor: '', js: 'androidColor', scss: 'androidColor' },
    { color: iosColor, name: 'iOS', type: '', classColor: '', js: 'iOSColor', scss: 'iOSColor' },
    { color: macColor, name: 'Mac', type: '', classColor: '', js: 'macColor', scss: 'macColor' },
    { color: windowsColor, name: 'Windows', type: '', classColor: '', js: 'windowsColor', scss: 'windowsColor' },
    {
        color: googlePlaystoreColor,
        name: 'Google playStore',
        type: '',
        classColor: '',
        js: 'googlePlayStoreColor',
        scss: 'googlePlayStoreColor',
    },
    {
        color: youtubeWatchpageColor,
        name: 'Youtube watch page',
        type: '',
        classColor: '',
        js: 'youtubeWatchpageColor',
        scss: '',
    },
    {
        color: televisionColor,
        name: 'Television',
        type: '',
        classColor: '',
        js: 'televisionColor',
        scss: 'televisionColor',
    },
    {
        color: fullyConversedColor,
        name: 'Fully conversed',
        type: 'not in platform',
        classColor: '',
        js: 'fullyConversedColor',
        scss: '',
    },
];
export const knwonColors = [
    { color: ch_knownColor, name: 'known', type: '', classColor: '', js: 'knownColor', scss: 'knownColor' },
    { color: ch_unKnownColor, name: 'Unknown', type: '', classColor: '', js: 'unKnownColor', scss: 'unKnownColor' },
    {
        color: ch_identifiedColor,
        name: 'Identified',
        type: '',
        classColor: '',
        js: 'identifiedColor',
        scss: 'identifiedColor',
    },
];
export const othersColors = [
    { color: blueColor, name: 'Blue', type: '', classColor: '', js: 'blueColor', scss: 'blueColor' },
    {
        color: blueLightColor,
        name: 'Blue light',
        type: '',
        classColor: '',
        js: 'blueLightColor',
        scss: 'blueLightColor',
    },
    { color: greenColor, name: 'Green', type: '', classColor: '', js: 'greenColor', scss: 'greenColor' },
    {
        color: greenLightColor,
        name: 'Green light',
        type: '',
        classColor: '',
        js: 'greenLightColor',
        scss: 'greenLightColor',
    },
    { color: yellowColor, name: 'Yellow', type: '', classColor: '', js: 'yellowColor', scss: 'yellowColor' },
    { color: orangeColor, name: 'Orange', type: '', classColor: '', js: 'orangeColor', scss: 'orangeColor' },
    { color: cyanColor, name: 'Cyan', type: '', classColor: '', js: 'cyanColor', scss: 'cyanColor' },
    {
        color: greyLightColor,
        name: 'Grey light',
        type: '',
        classColor: '',
        js: 'greyLightColor',
        scss: 'greyLightColor',
    },
    {
        color: greyDarkColor,
        name: 'Grey dark',
        type: '',
        classColor: '',
        js: 'greyDarkColor',
        scss: 'greyDarkColor',
    },
    { color: othersColor, name: 'Others', type: '', classColor: '', js: 'othersColor', scss: 'othersColor' },
];
export const chartCommonColors = [
    { color: ch_color1, name: 'Chart 1', type: '', classColor: '', js: 'ch_color1', scss: 'ch_color1' },
    { color: ch_color2, name: 'Chart 2', type: '', classColor: '', js: 'ch_color2', scss: 'ch_color2' },
    { color: ch_color3, name: 'Chart 3', type: '', classColor: '', js: 'ch_color3', scss: 'ch_color3' },
    { color: ch_color4, name: 'Chart 4', type: '', classColor: '', js: 'ch_color4', scss: 'ch_color4' },
    { color: ch_color5, name: 'Chart 5', type: '', classColor: '', js: 'ch_color5', scss: 'ch_color5' },
    { color: ch_color6, name: 'Chart 6', type: '', classColor: '', js: 'ch_color6', scss: 'ch_color6' },
    { color: ch_color7, name: 'Chart 7', type: '', classColor: '', js: 'ch_color7', scss: 'ch_color7' },
    { color: ch_color8, name: 'Chart 8', type: '', classColor: '', js: 'ch_color8', scss: 'ch_color8' },
    { color: ch_color9, name: 'Chart 9', type: '', classColor: '', js: 'ch_color9', scss: 'ch_color9' },
];
