/**
 * RDS connect form field labels — no Placeholders barrel import (prod TDZ).
 * Mirrors Constants/GlobalConstant/Placeholders RDS field placeholders.
 */
export const RDS_FIELD_LABEL = Object.freeze({
    ACCESSKEY: 'Access key',
    ACCESSTOKEN: 'Access token',
    ACCOUNT: 'Account',
    APIHOST: 'Api host',
    APITOKEN: 'API token',
    API_KEY: 'API key',
    AUTH_URL: 'Auth URL',
    CATALOG: 'Catalog',
    CLIENTID: 'Client ID',
    CLIENTSECRET: 'Client secret',
    CONSUMER_KEY: 'Consumer key',
    CONSUMER_SECRET: 'Consumer secret',
    DATABASE: 'Database',
    DATABASE_NAME: 'Database name',
    DATASETINFO: 'Dataset info',
    DOMAIN_URL: 'Domain URL',
    EMAIL: 'Email address',
    ENTER_URL: 'Enter URL',
    HOST: 'Host',
    HTTPPATH: 'HTTP path',
    HUBID: 'Hub ID',
    KEY: 'Key',
    KEYSPACE: 'Keyspace',
    NAMESPACE: 'Namespace',
    PASSWORD: 'Password',
    PORT: 'Port',
    PROJECTINFO: 'Project info',
    PROJECTKEY: 'Project key',
    PROJECTNAME: 'Project name',
    RESOURCEURL: 'Resource URL',
    SCHEMA: 'Schema',
    SECRETKEY: 'Secret key',
    SECURITYTOKEN: 'Security token',
    SERVER: 'Server',
    SHOPNAME: 'Shop name',
    SITEID: 'Site ID',
    SPREADSHEETID: 'Spreadsheet ID',
    STOREHASH: 'Store hash',
    STORENAME: 'Store name',
    STOREURL: 'Store URL',
    TENANTID: 'Tenant ID',
    URL: 'URL',
    USER_NAME: 'Username',
});
